//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Казакова
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class КазаковаEntities : DbContext
    {
        private static КазаковаEntities ZK = null;

        public static КазаковаEntities Get()
        {
            if (ZK == null)
                ZK = new КазаковаEntities();
            return ZK;
        }
        public КазаковаEntities()
            : base("name=КазаковаEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Задание> Задание { get; set; }
        public virtual DbSet<ЗадачиСотрудники> ЗадачиСотрудники { get; set; }
        public virtual DbSet<Клиенты> Клиенты { get; set; }
        public virtual DbSet<ПодЗадание> ПодЗадание { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
    }
}
