//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Казакова
{
    using System;
    using System.Collections.Generic;
    
    public partial class Задание
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Задание()
        {
            this.ПодЗадание = new HashSet<ПодЗадание>();
        }
    
        public int КодЗадание { get; set; }
        public string НазваниеЗадачи { get; set; }
        public System.DateTime Начала { get; set; }
        public System.DateTime Окончание { get; set; }
        public bool СтатусЗадания { get; set; }
        public int Клиент { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПодЗадание> ПодЗадание { get; set; }
    }
}
